(function(){
	
	views.add('article', function() {
		
		// This here is the constructor function for this view.
		// In here we can define some default locally scoped variables or do some other stuff.
		// In this view right now, we don't need to use the constructor at all.
		
	}, {
		
		onStart: function() {
		
			// Every view has an onStart() and an onEnd() function.
			// Everything that the view creates in onStart() *should* be removed in onEnd()
			// (the view instance is released from the memory upon stopping anyway but it is
			// a good idea to take care of removing any DOM elements generated by the view).

			this.box = $('<article>');
			
			this.titleElem = $('<h1>')
				.html(this.article.title)
				.appendTo(this.box);
			
			this.authorElem = $('<small>')
				.html('By ' + this.article.author)
				.addClass('author')
				.appendTo(this.box);
			
			this.contentElem = $('<div>')
				.addClass('content')
				.html(this.article.content)
				.appendTo(this.box);
			
			this.box
				.hide()
				.appendTo(this.container)
				.fadeIn(100);
			
		},
		
		onStop: function() {
			this.box.remove();
		}

	});
	
}());